### ISSUE TITLE
GET SENSORS FROM 

### ISSUE THREAD

**Issue by q1an-w** [q1an-w/390#16]
Hello ELEC/COEN 390 Students

As mentioned in the project document, the project will be done in 3 Sprints of 2 weeks each. The first Sprint will start week of Oct 16. 

I have a variety of sensors and development boards that the teams can borrow for use in their projects. This list can be found on moodle page in project section. You can use any materials you wish for your project, but you are responsible for procuring the materials not on the list and you will not be reimbursed for what you buy. I also have android phones that can be borrowed for your use. Any materials borrowed has to be returned after the final demo in its original condition. Your grades will not be released until the all the material is returned.

My office hours to borrow materials will be Tuesdays to Fridays between 9:30am to 4:30pm (subject to change) but with appointments only. I am located in room H851-1

If you wish to borrow any materials and/or phone, please send me an email at pbipin@ece.concordia.ca, clearly stating your team number and the material you wish to borrow. One of the team members will have to pass by my office to pick up the materials. Any emails without team number will be ignored.

Bipin Patel

pbipin@ece.concordia.ca

**Comment by pcarlss** [comment]
completed
